#!/usr/bin/env bash

set -e
# Unoffiical bash strict mode.
# See: http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -u
set -o pipefail

echo "This script allows testing of using a plutus script as a"
echo "stake credential. Files for addresses and certificates are"
echo "generated by this script."


source consts.sh
export CARDANO_NODE_SOCKET_PATH=${NODE_SOCK}

# create an address, with a script as a stake credential, along with stake
# address registration and delegation certificates

mkdir -p addresses certs queries

# create a payment address key
cardano-cli address key-gen \
            --verification-key-file addresses/payment-addr.vkey \
            --signing-key-file      addresses/payment-addr.skey

# create an address (with null stake credential)
cardano-cli address build \
            --payment-verification-key-file addresses/payment-addr.vkey \
            --testnet-magic ${TESTNET_MAGIC} \
            --out-file addresses/address.addr

# create an address (with script stake credential)
cardano-cli address build \
                --payment-verification-key-file addresses/payment-addr.vkey \
                --stake-script-file ${SCRIPTPATH} \
                --testnet-magic ${TESTNET_MAGIC} \
                --out-file addresses/address-script.addr

# create a stake address registration certificate
cardano-cli stake-address registration-certificate \
            --stake-script-file ${SCRIPTPATH} \
            --out-file certs/register-stake-address-script

# create a delegation certificate
# this will just pick the first pool in the list; if that pool does not
# deal out rewards (margin of 1, not actually creating blocks, ...),
# then the experiment will fail.
cardano-cli query stake-distribution \
            --testnet-magic ${TESTNET_MAGIC} \
            --out-file queries/stake-distribution

POOL=$(jq -r 'keys[0]' queries/stake-distribution)

cardano-cli stake-address delegation-certificate \
            --stake-script-file ${SCRIPTPATH} \
            --stake-pool-id ${POOL} \
            --out-file certs/delegate

cardano-cli stake-address delegation-certificate \
            --stake-script-file ${SCRIPTPATH} \
            --stake-pool-id ${POOL} \
            --out-file certs/delegate-script

echo "Files have been created."
echo
echo "Next, you will have to move some funds to this address:"
echo
cat addresses/address.addr
echo
echo
echo "Once the funds are at this address, continue with the script"
echo
echo "./createt-collateral"
echo
echo "which will move funds so that you have one UTxO entry for"
echo "collateral, and one at the address using a script stake credential."
echo
echo "Once that has taken effect on the chain, use"
echo
echo "./delegate.sh"
echo
echo "to actually delegate."
echo
echo "After rewards are in the reward address, you can withdraw them via"
echo
echo "./withdraw.sh"
